all:
  children:

    monitoring:
      hosts:
        monitoring01:
          ansible_host: 10.20.20.40
          ansible_user: ansible_user
          ansible_connection: ssh

    linux:
      hosts:
        debian-client:
          ansible_host: 10.10.10.101
          ansible_user: ansible_user
          ansible_connection: ssh

    windows:
      vars:
        ansible_connection: winrm
        ansible_user: 'MYHOMELAB\Administrator'
        ansible_password:  "{{ vault_windows_password | default(omit) }}"
        ansible_port: 5985
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore

      hosts:
        dc01:
          ansible_host: 10.20.20.10

        dc02:
          ansible_host: 10.20.20.11

        fs01:
          ansible_host: 10.20.20.20

        ca01:
          ansible_host: 10.20.20.30

        win11-client:
          ansible_host: 10.30.30.10
