---
- name: Test Linux connectivity
  hosts: linux
  gather_facts: false

  tasks:
    - name: Ping Linux hosts
      ansible.builtin.ping:

- name: Test Windows connectivity
  hosts: windows
  gather_facts: false

  tasks:
    - name: Ping Windows hosts
      ansible.windows.win_ping:
